### ISSUE TITLE
Error message on RedHat Linux with Java

### ISSUE THREAD

**Issue by Tracy51D** [51Degrees/device-detection-java#165]
### Background

Customer is blocked by the following exceptions when using device-detection.hash.engine.on-premise-4.4.77.jar and trying to deploy in RHEL 8.8 (Red-Hat Linux Machin 8.8)

Failed to instantiate [fiftyone.pipeline.core.flowelements.Pipeline]: Factory method 'devicePipelineProvider' threw exception; nested exception is java.lang.UnsatisfiedLinkError: The native library failed to load. This may mean that either the library itself or one of its dependencies is not accessible or not in the correct format for the target OS or architecture. A common missing library is libatomic1 on Linux. If this is the case, use your Linux package manager to install it on your system. If this is not possible, you may be able to use a different library by rebuilding the binary on the target system using the source code and instructions available on https://github.com/51degrees/device-detection-java. Inner error: /tmp/DeviceDetectionHashEngine-linux-x64.so9011770435092122370: /tmp/DeviceDetectionHashEngine-linux-x64.so9011770435092122370: failed to map segment from shared object

### Proposed solution

Run the following:
```sh
yum install cmake gcc-c++ libatomic
```
This should be enough to install the needed dependencies on RHEL.  

### Rationale

RHEL does not have apt-get, it has yum utility for package management.  

**Note**: As part of this issue we need to update the README to instruct how to install these dependencies on RHEL.

**Comment by sahithpaidi** [comment]
Hi @Tracy51D 
We have tried the proposed solution and updated the libatomic version in RHEL machine (Attached the log)
[out-2024-05-23 03_39_36.log](https://github.com/51Degrees/device-detection-java/files/15463891/out-2024-05-23.03_39_36.log)
But we are still facing the same issue, stating 
"`Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [fiftyone.pipeline.core.flowelements.Pipeline]: Factory method 'devicePipelineProvider' threw exception; nested exception is java.lang.UnsatisfiedLinkError: The native library failed to load. This may mean that either the library itself or one of its dependencies is not accessible or not in the correct format for the target OS or architecture. A common missing library is libatomic1 on Linux. If this is the case, use your Linux package manager to install it on your system. If this is not possible, you may be able to use a different library by rebuilding the binary on the target system using the source code and instructions available on https://github.com/51degrees/device-detection-java. Inner error: /tmp/DeviceDetectionHashEngine-linux-x64.so13855214620248637743: /tmp/DeviceDetectionHashEngine-linux-x64.so13855214620248637743: failed to map segment from shared object`"

Please help us to mitigate the issue and also please let us know 
1. Do we need to follow any other prerequisite apart from
https://github.com/51Degrees/device-detection-java/blob/main/README.md#pre-requisites ?
2. Do we need to have any executable permissions for /tmp folder?

**Comment by justadreamer** [comment]
Hi @sahithpaidi 

I am able to reproduce this exact error message when running in a container if I mount `/tmp` as a `noexec`, then the `mount` command output contains: 

```
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=777)
```

and when running an example I get the error message like you have.  This is because of the `noexec` flag - the system is unable to load dynamic libraries (which contain executable code) from `/tmp` directory.  java by default unpacks them into `/tmp` from the .jar. 

There are 2 workarounds:

1. Either provide `java.io.tmpdir` setting set to a different temporary directory, f.e. within a current working dir "./tmp".  on the command line it can be provided like so: 
```sh
java -Djava.io.tmpdir=./ ... 
```

2. Mount `/tmp` without a `noexec` flag - perhaps by adding a permanent entry into the [/etc/fstab](https://www.redhat.com/sysadmin/etc-fstab).  However RHEL has its reasons to mount /tmp as noexec, so we would rather discourage doing this and would suggest the first workaround, unless you know exactly that this won't violate f.e. conformance to certain security standards. 

Please let us know if the above worked or not and if not - we'd perhaps need more details on your setup.  Thanks.

**Comment by Tracy51D** [comment]
Hi @sahithpaidi 

As I've not heard back from you in awhile, I'm closing this issue. I've also sent a message via email. Please do get back in touch should you have any further issues.

Thanks
Tracy
