### ISSUE TITLE
v4 Random Crashes - Java 4.4.17 using on prem file

### ISSUE THREAD

**Issue by lh15** [51Degrees/device-detection-java#18]
Hi,

We are currently using 3.2.17.2 and have been for some time now.

We recently tried to upgrade to 4.4.17 (`com.51degrees:device-detection:4.4.17`) but have been experiencing random crashes.

1. Initially we thought it was because we didn't release the FlowData resource, but it still happened after that was fixed. See https://github.com/51Degrees/device-detection-java/issues/15#issuecomment-1108505620

2. Everything runs smoothly for a couple of hours and then at once, all servers crash. Memory and CPU don't really spike.

3. It seems to be a JNI crash. See screenshot. This is the only hint of an error we can find.

![image-20230310-165958](https://user-images.githubusercontent.com/23442414/226984255-5a8c1958-6696-4aaa-82a7-9406abb474b4.png)

**Comment by jwrosewell** [comment]
Java is one of our most popular API languages and is deployed in some very high performance environments. We're not aware of any similar reports from other users. However most users run on Linux versions so perhaps this relates to MSVC. 

We'll need more information to better understand what is happening in your situation. Can you provide the following.

1. Windows version
2. JVM and version
3. Code around the Process method of the Flowdata
4. Code around the building of the Pipeline and the engine configuration
5. Details concerning how you update the data file
6. How you create the windows native assembly for DD

Given that you're issue states that all servers crash at the same time can you confirm they all crash in the same way? 

One cause could relate to the data file update process. Perhaps a corrupt data file is being used to refresh the DD engine and it's triggered at the same time. This might then result in some memory conflict which prevents the VectorString (array) being generated.

Another unlikely cause could be that you have a type of request which occurs periodically which causes the crash. For example; a health check which some how is providing a specific type of input data which triggers this. I find this unlikely because there are a lot of tests around bad input data, but it's still a possibility.

What else is happening at the time of the crash?

**Comment by leibel-prodege** [comment]
I'm working on getting answers about windows versions etc.

5. We have a background job that pulls the new file every day. The code also checks if the file is there and if not, it downloads it

Here are the code answers:

4. The pipeline is a singleton. This happens on startup

```java
public void initFiftyOneDegreeData() throws Exception {
        if (!fiftyOneDegreeActive) {
            return;
        }

        ensureFileExists();

        providerReadWriteLock.writeLock().lock();
        try {
            pipeline = new DeviceDetectionPipelineBuilder()
                    .useOnPremise(dataFileV41Path, true)
                    .setPerformanceProfile(Constants.PerformanceProfiles.LowMemory)
                    .setDataUpdateLicenseKey(this.fiftyoneLicenseKeyV41)
                    .setAutoUpdate(false)
                    .build();

        } finally {
            providerReadWriteLock.writeLock().unlock();
        }
```

3. The flowdata is surrounded but a try-with-resources.

```java
 private DeviceInfo retrieveDeviceInfo(String useragent, int appVersionID, boolean isWebView, Long cacheKey, DeviceInfo di) {
        // Create a 'FlowData' instance from the Pipeline. This is used to pass data in and access results.
        // ****** ALWAYS ****** use "try with resources" to dispose the flowData when you are done.
        // https://github.com/51Degrees/device-detection-java/issues/15#issuecomment-1108505620
        try (FlowData data = pipeline.createFlowData()) {
            data.addEvidence("header.user-agent", useragent).process();
            DeviceData deviceData = data.get(DeviceData.class);
            di = createDeviceInfo(deviceData, useragent, appVersionID, isWebView);
            deviceInfoCache.put(cacheKey, di);
        } catch (Exception e) {
            log.debug("Error matching userAgent: " + useragent, e);
        }
        return di;
    }
    ```

**Comment by leibel-prodege** [comment]
Answers the the windows questions:

- windows server 2019 , 10.0.17763 Build 17763

- java jdk 1.8.0. 201-b09

- see resin screen shot.  Resin 4.0.66 with JDK version, memory,  The mdmp file was generated in the base folder of Resin (c:\Java\Resin4).  Maybe from “JVM or windows” crash, Resin generates mdmp file, and Resin restarts.  We could reach out to Resin to see what they think of the mdmp file in their base folder.


![1f3242c8-ab32-4fd7-87ec-9952318f5d79](https://user-images.githubusercontent.com/128666115/228703355-75a46fbe-7771-414d-abc8-467d152ff10b.png)

**Comment by kirstin51D** [comment]
Hi @leibel-prodege! Have you had a chance to look at James' suggestions above, particularly about using the auto update feature of the API? I believe you also spoke to my colleague about using the cloud API instead of on-premise, so if you have any questions on that, do let me know and we can discuss via email. 

Let me know your thoughts! If we haven't heard back, we will look to close our internal support ticket for this issue by the end of next week. Thanks!
